### ISSUE TITLE
Is the intention of "node-set" to be a shim for the native Set?

### ISSUE THREAD

**Issue by rwaldron** [pvorb/node-set#1]
Reference: http://wiki.ecmascript.org/doku.php?id=harmony:simple_maps_and_sets

**Comment by pvorb** [comment]
I didn't know Harmony's `Set` class. In some way it is a shim, but it doesn't have the same method names. It's only a very generic implementation of sets on top of regular JS objects.

**Comment by pvorb** [comment]
I think I'll add the missing method names so it can be used as a shim.

**Comment by pvorb** [comment]
Check out version 0.3.0. :)
