### ISSUE TITLE
remove Set::contains?

### ISSUE THREAD

**Issue by bobzoller** [pvorb/node-set#4]
Would you accept a pull request to remove `Set::contains` and just leave `Set::has`?  `contains` is not in the current ES6 spec.  I'm using node-set as a backfill for browsers without a native Set, Firefox just bit me because SpiderMonkey provides a native Set, but it follows the current spec and does not include `contains`. Thoughts?

**Comment by pvorb** [comment]
Hm... Not sure about this. When I created the project I didn't plan to create a shim for the ES6 `Set`. I think that `contains` is a much more descriptive name for that method, so first there was `contains` and then I added `has` to be ES6 compatible.

Of course I could remove these methods, but this would break compatibility with legacy code. Another solution (wich I'd prefer) would be to remove the documentation for all methods that are not in ES6's `Set`. This way, old code would still be usable, while new users usually wouldn't use these old method names unless they take a look at the implementation. For those users I'd add a deprecation comment in front of the definitions.

Thoughts?
