### ISSUE TITLE
Storing objects in Set

### ISSUE THREAD

**Issue by DeTeam** [pvorb/node-set#5]
This will log `true`. However `b` is not in set.

``` javascript
var s = new Set();
var a = {name: "A"};
var b = {name:"B"};
s.add(a);

console.log(s.contains(b));
```

That's caused by implementation (`this.set = {}` and then storing items in keys).
Guess that's not correct behavior for a polyfill ? (%

**Comment by pvorb** [comment]
You're right. I'll fix that.

**Comment by DeTeam** [comment]
If you're not very concerned about perfomance, you may try Array + indexOf/lastIndexOf (there's already a set implementation based on `[]`).
